version: "3.9"

services:
  app:
    image: suryanshgarg/developerhub:latest   # pulls from Docker Hub
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/devhub
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    restart: unless-stopped
